name: Deploy Subsocial docs to f3joule.github.io

on:
  push:
    branches: [ main ]

jobs:
  deploy-docs:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 14.x ]
#        gh-pages-cname: [ 'sub.id' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Yarn dependencies
        run: yarn install
      - name: Build Docusaurus
        run: yarn build
      - name: Deploy build directory to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: f3joule/f3joule.github.io
          publish_dir: ./build
#          cname: ${{ matrix.gh-pages-cname }}
